[Arguments]

# project options
port = 8097
env = main
same_env = Yes
save_results = Yes

project_name = RNN_SLM
result_subdir = RNN_SLM-Wikitext2
monitor={"metric": "loss", "decreasing": 1}


# model options
model_type = RNN_SLM
model_options = {"vocab_size": 4000, "embed_dim": 256, "hidden_dim": 256, "num_layers": 2, "dropout": 0.2}



; dataset = Wikitext2
dataset = GPT2

dataset_options = {"seed": 0, "ratio_train": 0.7, "ratio_test": 0.2, "block_size": 256}


features_path = ./data
ndim = 130

# model options
precision = 16
batch_size_test = 256
batch_size_val = 256
batch_size_train = 256
; resume = results/2Pulse-SAEFit/09-23__19-56-02--init_95/checkpoints/2Pulse-SAEFit-epoch=1399-val_loss=0.001.ckpt


# EarlyStopping
EarlyStopping=True
earlystop_options = {"monitor":"val_loss", "min_delta":0.0001, "patience":7, "verbose":1, "mode":"min"}


lam = 0.01


#loss_type = Regression
#loss_options = {"reduction": "mean"}
loss_type = Classification


evaluation_type_1 = Accuracy
evaluation_options_1 = {"task": "multiclass", "num_classes": 4000}




control_type = RNN_SLM

manual_seed = 0
nepochs = 1000
init_epochs = 15
check_val_every_n_epochs = 2

optim_method = AdamW
; optim_method = SGD

learning_rate = 1e-3

# AdamW
optim_options = {"weight_decay": 1e-4}
gradient_clip = 3.0

# SGD
; optim_options = {"momentum": 0.9, "weight_decay": 2e-5}

scheduler_method = StepLR
scheduler_options = {"step_size": 50, "gamma": 0.8}

; scheduler_method = MultiStepLR
; scheduler_options = {"milestones": [74], "gamma": 0.5}
; scheduler_method = CustomMultiGammaLR
; scheduler_options = {"milestones": [10, 20, 30, 100, 500], "gammas": [0.5, 0.8, 0.8, 0.8, 0.5]}


# cpu/gpu settings
ngpu = 1
nthreads = 1
