#!/bin/bash --login
########## SBATCH Lines for Resource Request ##########
 
#SBATCH --time=$minutes:00             # limit of wall clock time - how long the job will run (same as -t)
#SBATCH --nodes=1                   # number of different nodes - could be an exact number or a range of nodes (same as -N)
#SBATCH --ntasks=1                  # number of tasks - how many tasks (nodes) that you require (same as -n)
#SBATCH --cpus-per-task=$cores           # number of CPUs (or cores) per task (same as -c)
#SBATCH --mem-per-cpu=32G            # memory required per allocated CPU (or core) - amount of memory (in bytes)
#SBATCH --job-name $exp_name-exp       # you can give your job a name for easier identification (same as -J)
#SBATCH --output=../jobs_outputs/$exp_name.out    # output file to write the log to

########## Command Lines for Job Running ##########

export PATH=$PATH:/mnt/research/$username/miniconda3/bin
module load Conda/3

conda activate crl

cd /mnt/research/hal/$username/controllable-representation-learning

echo $train_command

date

srun $train_command

echo $test_command_1

date

srun $test_command_1

date

conda deactivate
